### ISSUE TITLE
for all the windows users

### ISSUE THREAD

**Issue by hoebat** [canweriotnow/lein-ruin#5]
format c drive (it's their fault anyways)

**Comment by canweriotnow** [comment]
I'd like to open an issue that now "all the windows users" is running tthrough my head to the tune of Beyoncé's "all the single ladies"

**Comment by hoebat** [comment]
"if you _ruin_ed it you should have put an antivirus on it…."

**Comment by hoebat** [comment]
oh oh oh, oh oh oh, noooo... (to the same tune)

**Comment by canweriotnow** [comment]
Beyonce seems to be unavailable to open a PR, so I'm going to close this for now.

**Comment by hoebat** [comment]
damn it. it would've been one hell of a hit
